### ISSUE TITLE
Save button in Diagram\DiagramRibbonUI does not work

### ISSUE THREAD

**Issue by ricklxm** [telerik/xaml-sdk#11]
Run this demo application ([Diagram\DiagramRibbonUI ](https://github.com/telerik/xaml-sdk/tree/master/Diagram/DiagramRibbonUI)) in visual studio, and drag and drop a diagram item into the RadDiagram canvas. Then click Save menu. You can see that the SaveFileDialog does not pop up. But if I click the gallery bar before click Save menu, then it works well.
Could anyone kindly tell me how to fix this?

Thanks very much!

**Comment by ricklxm** [comment]
I'm using UI for WPF Q3 2015\\Binaries\WPF40

**Comment by martinivanoff** [comment]
Hello ricklxm,

Thank you for reporting this. We've fixed it on our side and the fix will be available in the next couple of days. Basically, the issues was that the Save and Open commands rely on the element with name set to 'root'. This should be the Example UserControl. However, the x:Name property of the control wasn't set and the commands couldn't call their Execute handlers in some cases. The fix was to set the x:Name property of the Example control to 'root'.

Regards,
Martin Ivanov
