### ISSUE TITLE
Filter is not working in multimodel binding

### ISSUE THREAD

**Issue by PKYADAV** [telerik/xaml-sdk#27]
Dear Team,

I am trying to bind multi models data to grid view as below:

```
{
    "id": "id1001",
    "booking_date": "09-AUG-2019 18:45:00 +05:30",
    "bookingtype": "MARKETPLACE",
    "type": "booking",
    "customer": {
        "id": "CUST1001",
        "name": "PRAVIN YADAV",
        "mobileno":"9990285656"
    },
    "createdby": "SC1005",
    "createddate": "09-AUG-2019 18:45:00 +05:30",
    "updatedby": "SC1005",
    "updateddate": "09-AUG-2019 18:45:00 +05:30",
    "_rid": "RwgzANM6dFcBAAAAAAAAAA==",
    "_self": "dbs/RwgzAA==/colls/RwgzANM6dFc=/docs/RwgzANM6dFcBAAAAAAAAAA==/",
    "_etag": "\"00000000-0000-0000-4f1d-d5c1c51601d5\"",
    "_attachments": "attachments/",
    "_ts": 1565401763
}
```

Filter is not available on customer id or name.

**Comment by martinivanoff** [comment]
Hello PKYADAV,

Can you tell me more about this json data? Is this used with RadGridView for WPF? If so, how? 

Regards,
Martin Ivanov
Technical Support Engineer
Telerik UI for WPF

**Comment by PKYADAV** [comment]
Hi, Thanks for your response !!

We have created dynamic class as given in telerik forum and we are parsing Json from CosmosDb query.

Filter is showing and working for outer json but when we add inner filed (customer.id, customer.name in above json). Filter is disabled on those columns.

Please suggest, if we are doing wrong and any work around.

**Comment by martinivanoff** [comment]
Hello PKYADAV,

It is possible that the issue comes from the following bug in the control.
[https://feedback.telerik.com/wpf/1405533-gridview-columns-showing-properties-of-a-sub-class-cannot-be-sorted-or-filtered](https://feedback.telerik.com/wpf/1405533-gridview-columns-showing-properties-of-a-sub-class-cannot-be-sorted-or-filtered)

However, I can't tell what exactly happens only by the provided data. What I can suggest you is to open a new [ticket](https://www.telerik.com/account/support-tickets) and attach a runnable sample showing the issue there. You can also post your question in the [forum](https://www.telerik.com/forums/wpf/gridview) with some runnable code.

I am closing this Issue because we can't relate it to a functionality of an SDK example. It seems a generic issue or customization of RadGridView

Regards,
Martin Ivanov
Technical Support Engineer
Telerik UI for WPF
